### PR TITLE
sql: Replace similar tables with templated queries

### PR DESCRIPTION
**Pull request by Bjwebb**
https://github.com/open-contracting/kingfisher-summarize/issues/139

### CODE REVIEW

**Comment by Bjwebb** [comment]
@jpmckinney This is only some of the suggested tables, but I thought it might be useful for you to review the approach before I proceed with the rest.

**Review by jpmckinney — COMMENTED** [review]
Looks good! I'm wondering whether we can use fewer parameters, e.g. object_name, group_name, sql_fragment like:

* `'tender', 'tender', ''`
* `'award', 'awards', 'award_index,'`
* `'contract', 'contracts', 'contract_index,'`

That way, there are even fewer opportunities for typos.

**Comment by jpmckinney** [comment]
Also, calling EXECUTE all in one file means that this file will need to wait for tender, award, and contract dependencies to complete, which will make Summarize a little slower. Can we instead have the CREATE TABLE query in a function, and call the function from separate files, so that Summarize can schedule them more aggressively?

**Review by jpmckinney — APPROVED** [review]
I extracted a method in a commit.

Nitpicks in another commit: RST is 3-space indent. US spelling.

**Pull request merged**
